### ISSUE TITLE
4.1 Dump issue

### ISSUE THREAD

**Issue by TimmieDevelops** [Encryqed/Dumper-7#11]
some reason i cannot dump the file  4.1 season

![image](https://user-images.githubusercontent.com/79818585/229250198-b617ead2-6cf4-43d7-b8ce-84d2afdbe5c3.png)

**Comment by Fischsalat** [comment]
Well, at least you've sent some actually useful information, instead of just saying "4.1 crash help".

Sadly this information shows that you clearly haven't read the Readme file. Els you would know, that the FProperty-Experimental branch was made for Season 12 (UE4.25) and later.

For S0 - S12 use the main branch.
