### ISSUE TITLE
Access Violation, UE 4.10.4 Sea of thieves 

### ISSUE THREAD

**Issue by Nythys** [Encryqed/Dumper-7#156]
![image](https://github.com/Encryqed/Dumper-7/assets/122648994/d17f0c50-0e48-48e5-adcd-011a522a81ad)
![image](https://github.com/Encryqed/Dumper-7/assets/122648994/f8eb5573-75b8-4722-aaa8-882e203a898a)
![image](https://github.com/Encryqed/Dumper-7/assets/122648994/0e4953c2-27d6-4756-9428-2ead0c8ce101)

The dumper crashes when I inject it into sea of ​​thieves, I have already seen an issue on this game but I was wondering if there is a solution now?

**Comment by Fischsalat** [comment]
There is no solution. You can get the dumper to at least generate an sdk if you replace all checks for EClassCastFlags::EnumProperty with checks for the UClass. But that wont really help you because the SDK is so cyclic nothing will compile. 

So yea, there's not going to be any SoT support anytime soon.
