### ISSUE TITLE
 static_assert errors

### ISSUE THREAD

**Issue by WeebleWooble** [Encryqed/Dumper-7#208]
![1](https://github.com/user-attachments/assets/cc1ba6c1-f675-48b0-8c9f-8efb293199c9)
![2](https://github.com/user-attachments/assets/691ad137-1b34-4d18-bd48-c249e4934489)

[4.16.3-0+++UE4+Release-4.16-NARUTO.zip](https://github.com/user-attachments/files/16484951/4.16.3-0%2B%2B%2BUE4%2BRelease-4.16-NARUTO.zip)

I'm lost in these errors like in a forest

**Comment by Fischsalat** [comment]
For some reason the game modified TSet to be 0x80 instead of 0x50.

To fix this properly you'd need to reverse engineer their TSet implementation. But instead of doing that you could just add 0x30 padding at the end of TSet and just never access any TSet/TMap. After adding the padding you need to change the static_asserts asserting that `sizeof(TSet) == 0x50` and `sizeof(TMap) == 0x50)` (both in UnrealContainers.hpp). You also need to remove the 0x30 padding at the end of UDataTable.

One last bug unrelated to the one above is a struct without members that contains 1 byte of padding. Just remove the padding there.
![image](https://github.com/user-attachments/assets/bbee81b1-d398-4a42-b932-0acb5eb40303)
![image](https://github.com/user-attachments/assets/030c62f4-b8de-4d62-a224-1a2a8b61b45a)

**Comment by WeebleWooble** [comment]
> По какой-то причине игра изменила TSet на 0x80 вместо 0x50.
> 
> Чтобы исправить это должным образом, вам нужно будет провести обратную разработку их реализации TSet. Но вместо этого вы можете просто добавить отступ 0x30 в конец TSet и просто никогда не обращаться ни к какому TSet/TMap. После добавления отступа вам нужно изменить static_asserts, утверждающий, что `sizeof(TSet) == 0x50`и `sizeof(TMap) == 0x50)`(оба в UnrealContainers.hpp). Вам также нужно удалить отступ 0x30 в конце UDataTable.
> 
> Последняя ошибка, не связанная с предыдущей, — это структура без членов, которая содержит 1 байт заполнения. Просто удалите заполнение там. ![изображение](https://private-user-images.githubusercontent.com/64608145/354895499-bbee81b1-d398-4a42-b932-0acb5eb40303.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3Nzk5MzcsIm5iZiI6MTcyMjc3OTYzNywicGF0aCI6Ii82NDYwODE0NS8zNTQ4OTU0OTktYmJlZTgxYjEtZDM5OC00YTQyLWI5MzItMGFjYjVlYjQwMzAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDEzNTM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3ZDJmNmJmNjdkMTlmOTg3NjNmMDgwODM2YWY0MDc4NDY2MWI0MGJkMWU4ZTUwZDZlNzdlYjgwNWM1NjAwODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v5s6w2GggW-deHW3K1edKl-OesB7AOO8aFn8vTBI1Pc) ![изображение](https://private-user-images.githubusercontent.com/64608145/354895580-030c62f4-b8de-4d62-a224-1a2a8b61b45a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3Nzk5MzcsIm5iZiI6MTcyMjc3OTYzNywicGF0aCI6Ii82NDYwODE0NS8zNTQ4OTU1ODAtMDMwYzYyZjQtYjhkZS00ZDYyLWEyMjQtMWEyYThiNjFiNDVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDEzNTM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1Y2FkYWI0M2NhNWU4NWM2MDJmZWFkZTdjMTU4MDJmYzIzYTA1MTQyNWY4MWYxZWM5ODUyNDc4YzcwMTI1M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FZ7UlgC0bw4QoFFbBCu9OuAq99zXPgkzQEhGxw2lJCY)

thank you very much

**Comment by WeebleWooble** [comment]
yes, that helped, thanks

**Comment by WeebleWooble** [comment]
The question is relevant again after the latest game update, similar issues. The above does not help anymore

**Comment by Fischsalat** [comment]
well, open a new issue with proper information then
