### ISSUE TITLE
[FR] Support for USmap dumping?

### ISSUE THREAD

**Issue by Kein** [Encryqed/Dumper-7#232]
Talking about this:
https://github.com/TheNaeem/UnrealMappingsDumper

I know that [Dumper-7](https://github.com/Encryqed/Dumper-7) produces its own `usmap` dump but it is in different format and not compatible with most tools that rely on mapping dumps.

**Comment by Fischsalat** [comment]
The `.usmap` file generated is supposed to be compatible with [CUE4Parse](https://github.com/FabianFG/CUE4Parse) (for FModel). It contains some minor diversions from the original format, in order to fix issues with the format. 

**Changes:**
-  [Large enums](https://github.com/Encryqed/Dumper-7/commit/dbeb5ed2779fbdead1ac7cf0c12a44e2996e1d10#diff-52a388acf3484d9babb3097ac1ac52c4651e19f1fb35e3961f0604b1d1fc3b26R276):
    ```diff
    // Dumper-7
    -WriteToStream(Data, static_cast<uint8>(Enum.GetNumMembers()));
    +WriteToStream(Data, static_cast<uint16>(Enum.GetNumMembers()));
    ```
    ```c#
    // CUE4Parse
    Ar.Version >= EUsmapVersion.LargeEnums ? Ar.Read<ushort>() : Ar.Read<byte>();
    ```
- [Long Names](https://github.com/Encryqed/Dumper-7/commit/bba34b3dc47d1e305a5a1a0ed9bc3ebba33efc39#diff-52a388acf3484d9babb3097ac1ac52c4651e19f1fb35e3961f0604b1d1fc3b26R126):
    ```diff
    -Buffer.Write<uint8>(StrName.length());
    +NameTable << static_cast<uint16>(Name.length());
    ```
    ```c#
    // CUE4Parse
    Ar.Version >= EUsmapVersion.LongFName ? Ar.Read<ushort>() : Ar.Read<byte>();
    ```

There is no plan to support the old file versions, as they can't handle the full sizees of enums or lenghs of names. Instead other parsers for `.usmap` files should support the newer (fixed) versions, doing so doesn't take a lot of effort (see above examples).

**Comment by Kein** [comment]
Ah, I see, makes sense

**Comment by Kein** [comment]
I see. It is definitely not compatible with CUE4Parse current master.
Though my question is how minor these changes? The usmap dumped by D7 is 50% of the size of the old format and contains no readable data. Is it compressed?

**Comment by Fischsalat** [comment]
That seems very very strange.

Value written for the compression enum:
![image](https://github.com/user-attachments/assets/b9d61de9-f454-425b-9b05-e40dec69a1c7)

CompressionMethod enum:
![image](https://github.com/user-attachments/assets/b12dafaf-a3b4-439c-a49b-929b435ed31c)

Default value for compression:
![image](https://github.com/user-attachments/assets/bf62b178-84a7-4c25-9559-98ee04133a2c)

**Comment by Kein** [comment]
Well it is really odd since FModel can't read this new format. Havent really tried to debug, just assumed, according to your words, it is supported and tested it.
