### ISSUE TITLE
Implementing FindObjects for UE4 SDKs

### ISSUE THREAD

**Issue by Aeyth8** [Encryqed/Dumper-7#253]
I'm a new reverse engineer, so you can simply call me dumb or call this a skill issue.

But I've been struggling to understand how to list all UObjects in an array/vector, so I (re)implemented the FindObjects function, and it works perfectly in my use-case. 
*(I unfortunately learned reverse engineering while relying on FindObjects)*

If you could add this to the SDK generator, this would make mine, and plenty of other beginner projects so much easier to work on. 

```cpp 
template<typename T>
static std::vector<T*> FindObjects()
{
	std::vector<T*> ret;
	auto v = T::StaticClass();
	for (int i = 0; i < SDK::UObject::GObjects->Num(); ++i)
	{
		auto object = SDK::UObject::GObjects->GetByIndex(i);

		if (!object)
			continue;

		if (object->IsA(v))
			ret.push_back(static_cast<T*>(object));
	}
	return ret;
}
```

And here's an example of how I used this in my code:
```cpp
void PIDs() {
	for (SDK::ASCTPlayerState* States : FindObjects<SDK::ASCTPlayerState>()) {
		std::cout << States->SteamUserID << std::endl;
		std::cout << States->PSNID << std::endl;
		std::cout << States->SessionID << std::endl;
		std::cout << States->ABUserID << std::endl;
	}
}
```

Another example is 
```cpp
template <typename T>
T* GetLastOf() {
	return FindObjects<T>().back();
}

void Travel() {
	GetLastOf<SDK::ASCTGameMode_Warmup>()->TravelToStartingArea();
}
```

**Comment by Fischsalat** [comment]
I'm not really a fan of `FindObjects` as it is quite inefficient. It's similar to choosing JavaScript over C++, it's easier but slower.

Your first usage example already displays this, as you're iterating over all objects in GObjects, just to iterate over some of them for a second time. Instead of doing it like that you could've performed that action in the GObjects loop already.

And your second example is quite dangerous, as you can't be sure that you always want to use the last object of some type.

All in all I'm not planning on adding that function to the SDK.

**Comment by Aeyth8** [comment]
Could you please tell me the "proper" way that I should be doing instead?
I've been struggling to find another method.

Thanks

**Comment by Fischsalat** [comment]
For actors for example it's faster to iterate over the `TArray<AActor*> Actors;` in a ULevel instance (`UWorld::PersistentLevel` should contain most of the actors you care about, for the rest iterate the levels array somewhere). 

For any other types I would recommend you to get instances of them by going through some pointer chain like 
`World->SomeVar->AnotherVar->MyInventory`. If that isn't an option because you can't find any instance of that class or a super-type of it, you can still iterate over GObjects, but perform the action in the loop directly, rather than first collecting the instances and looping over them again.

**Comment by Aeyth8** [comment]
I see, thank you very much I will be referencing back to this while I work on programming.
