### ISSUE TITLE
Crashes a few seconds after inject on Fortnite. Anti-cheat disabled.

### ISSUE THREAD

**Issue by coby69** [Encryqed/Dumper-7#50]

**Comment by Fischsalat** [comment]
FName::AppendString was inlined. And the fallback is GNames, which is encrypted. Oof.

**Comment by gamerbross** [comment]
so?

**Comment by TimmieDevelops** [comment]
So which means it can not get a dump or something?

**Comment by Fischsalat** [comment]
not for now

**Comment by TimmieDevelops** [comment]
rip

**Comment by Fischsalat** [comment]
stop uselessly commenting on github issues.

**Comment by Milxnor** [comment]
> FName::AppendString was inlined. And the fallback is GNames, which is encrypted. Oof.

Time to switch to FName::ToString!

**Comment by Fischsalat** [comment]
Wow, thanks for the great tip, it will work perfectly (it's also inlined).

**Comment by Twin1dev** [comment]
😭

**Comment by Milxnor** [comment]
> Wow, thanks for the great tip, it will work perfectly (it's also inlined).

Switch to GetObjectName then

**Comment by Milxnor** [comment]
> Wow, thanks for the great tip, it will work perfectly (it's also inlined).

KismetStringLibrary::Conv_NameToString!!

**Comment by Fischsalat** [comment]
I'll take a look at it once I finished the rewrite.

**Comment by Fischsalat** [comment]
Apparently one of the two "FName::ToStrings" overloads isn't inlined and is called by Conv_NameToString. I'm confused, as always.

**Comment by Fischsalat** [comment]
This issue is now fixed on the GeneratorRewrite branch. However it is strongly advised to add FMemory::Free to the SDK. 

Instructions on adding FMemory::Free are displayed when compiling the SDK. 

Should the game crash curing generation try freezing Fortnite's process before generating the sdk. 
Should the console window not display the "SDK Generation took n seconds" message try to freeze the game earlier.

**Comment by Fischsalat** [comment]
GeneratorRewrite replaced main.
